name: 'Run textlint with reviewdog'
description: '🐶Run textlint with reviewdog on pull requests to improve document writing experience.'
author: 'Tsuyoshi CHO <Tsuyoshi.CHO+develop@Gmail.com>'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-check,github-pr-review].
      Default is github-pr-review.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-review'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_level:
    description: |
      Optional.  Exit code control for reviewdog, [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  fail_on_error:
    description: |
      Deprecated.

      Optional.  Exit code for reviewdog when errors are found [true,false]
      Default is `false`.

      If `true` is set, it will be interpreted as "-fail-level=error".
      But if "-fail-level" is set non-`none`, it will be ignored.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  textlint_flags:
    description: "flags and args of textlint command. Default: '.'"
    required: true
    default: '.'
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'textlint'
  package_manager:
    description: 'Package manager used in the repository [npm,yarn,pnpm,bun]'
    default: 'npm'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
      env:
        REVIEWDOG_VERSION: v0.20.3
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_LEVEL: ${{ inputs.fail_level }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_TEXTLINT_FLAGS: ${{ inputs.textlint_flags }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_PACKAGE_MANAGER: ${{ inputs.package_manager }}
branding:
  icon: 'alert-octagon'
  color: 'blue'
